#!/usr/bin/env python3
"""
WC3 地图构建器 - 基于官方规范
支持 WC3 1.27 (RoC/TFT)
"""

import struct
import sys
import os

# 常量
HM3W_SIGNATURE = b'HM3W'
W3E_SIGNATURE = b'W3E!'
MPQ_OFFSET = 512  # 标准 WC3 使用 512 字节偏移

# 地形纹理 ID (Lordaeron Summer)
GROUND_TEXTURES = [
    b'Ldrg',  # Grass
    b'Ldrt',  # Dirt
    b'Ldug',  # Grass Dark
    b'Ldry',  # Dirt Dark
    b'Ldsb',  # Grass Round
    b'Ldng',  # Dirt N
]

CLIFF_TEXTURES = [
    b'CLdi',  # Cliff Dirt
    b'CLgr',  # Cliff Grass
    b'CLsh',  # Cliff Shadow
]


def create_w3i_simple(map_name="Hello RPG", width=32, height=32):
    """创建 war3map.w3i - 简化版 (format_version=18, RoC/TFT)"""
    data = bytearray()

    # === 头部 (0x00 - 0x7C) ===
    # format_version: 18 = RoC/TFT
    data += struct.pack('<I', 18)  # 0x00

    # map_version
    data += struct.pack('<I', 1)   # 0x04

    # editor_version
    data += struct.pack('<I', 2)   # 0x08

    # name (null-terminated, max 64)
    name_bytes = map_name.encode('gbk') + b'\x00'
    data += name_bytes
    data += b'\x00' * (64 - len(name_bytes))  # 0x0C - 0x4B

    # author
    author = b"Wc3Forge\x00"
    data += author
    data += b'\x00' * (64 - len(author))  # 0x4C - 0x8B

    # description
    desc = b"Generated by Wc3Forge\x00"
    data += desc
    data += b'\x00' * (128 - len(desc))  # 0x8C - 0x10B

    # suggested_players
    players = b"2-12\x00"
    data += players
    data += b'\x00' * (32 - len(players))  # 0x10C - 0x12B

    # camera bounds (8 floats)
    half_w = width * 128 / 2
    half_h = height * 128 / 2
    data += struct.pack('<ffff', -half_w, -half_h, half_w, half_h)  # 0x12C - 0x13B
    data += struct.pack('<ffff', -half_w, half_h, half_w, -half_h)  # 0x13C - 0x14B

    # camera complement (4 ints)
    data += struct.pack('<IIII', 0, 0, 0, 0)  # 0x14C - 0x15B

    # playable area
    data += struct.pack('<II', width * 256, height * 256)  # 0x15C - 0x163

    # flags
    data += struct.pack('<I', 0x00000001)  # 0x164

    # tileset: 'L' = Lordaeron Summer
    data += b'L'  # 0x168

    # loading screen
    data += struct.pack('<I', 0)  # number
    data += b'\x00' * 260  # model path
    data += b'\x00' * 256  # text
    data += b'\x00' * 256  # title
    data += b'\x00' * 256  # subtitle

    # game data set
    data += struct.pack('<I', 0)  # 0

    # prologue
    data += b'\x00' * 260  # model
    data += b'\x00' * 256  # text
    data += b'\x00' * 256  # title
    data += b'\x00' * 256  # subtitle

    # fog (version >= 25)
    # 跳过，使用 version 18

    # === 玩家数据 ===
    # players count
    data += struct.pack('<I', 1)  # 1 player

    # Player 0 (人类玩家)
    data += struct.pack('<I', 0)   # internal number
    data += struct.pack('<I', 1)   # type (user)
    data += struct.pack('<I', 1)   # race (human)
    data += struct.pack('<I', 0)   # fixed start pos
    player_name = b"Player 1\x00"
    data += player_name
    data += b'\x00' * (24 - len(player_name))
    data += struct.pack('<ff', 0, 0)  # start x, y
    data += struct.pack('<II', 0, 0)  # ally priorities

    # 填充剩余 23 个玩家 (0xFF = empty)
    for i in range(23):
        data += struct.pack('<I', 0xFF)   # internal
        data += struct.pack('<I', 0)      # type
        data += struct.pack('<I', 0)      # race
        data += struct.pack('<I', 0xFFFF) # fixed
        data += b'\x00' * 24              # name
        data += struct.pack('<ff', 0, 0)  # pos
        data += struct.pack('<II', 0, 0)  # ally

    # === 势力数据 ===
    data += struct.pack('<I', 1)  # 1 force

    # Force 0
    data += struct.pack('<I', 3)  # flags (alliance + shared vision)
    data += struct.pack('<I', 0xFF)  # player mask (player 0)
    force_name = b"All Players\x00"
    data += force_name
    data += b'\x00' * (32 - len(force_name))

    # 填充剩余势力
    for i in range(15):
        data += struct.pack('<I', 0)
        data += struct.pack('<I', 0)
        data += b'\x00' * 32

    # === 升级/科技/随机表 ===
    data += struct.pack('<I', 0)  # upgrades
    data += struct.pack('<I', 0)  # tech
    data += struct.pack('<I', 0)  # random units
    data += struct.pack('<I', 0)  # random items

    return bytes(data)


def create_w3e_simple(width=32, height=32):
    """创建 war3map.w3e - 简化版"""
    data = bytearray()

    # === 文件头 ===
    data += W3E_SIGNATURE  # magic
    data += struct.pack('<I', 11)  # version

    # tileset: 'L' = Lordaeron Summer
    data += b'L'

    # uses_custom_tileset
    data += struct.pack('<I', 0)

    # ground tilesets count
    data += struct.pack('<I', len(GROUND_TEXTURES))

    # ground tileset IDs
    for tid in GROUND_TEXTURES:
        data += tid

    # cliff tilesets count
    data += struct.pack('<I', len(CLIFF_TEXTURES))

    # cliff tileset IDs
    for tid in CLIFF_TEXTURES:
        data += tid

    # map size (+1)
    data += struct.pack('<I', width + 1)
    data += struct.pack('<I', height + 1)

    # offsets
    offset_x = -(width + 1) * 128 / 2
    offset_y = -(height + 1) * 128 / 2
    data += struct.pack('<f', offset_x)
    data += struct.pack('<f', offset_y)

    # === Tilepoint 数据 ===
    # 每个 tilepoint: 7 bytes
    for y in range(height + 1):
        for x in range(width + 1):
            # ground_height (int16)
            ground_height = 0
            data += struct.pack('<h', ground_height)

            # water_height + boundary (int16) - 使用 unsigned
            water = 0
            boundary = 1 if (x == 0 or x == width or y == 0 or y == height) else 0
            water_height = water | (boundary << 15)  # bit 15 = boundary
            data += struct.pack('<H', water_height)  # unsigned short

            # flags + textures (4 bytes)
            # 4 bits: flags
            # 4 bits: ground texture
            # 3 bits: cliff variation
            # 5 bits: ground variation
            # 4 bits: cliff texture
            # 4 bits: layer height
            # = 24 bits = 3 bytes

            flags = 0
            if x == 0 or x == width or y == 0 or y == height:
                flags = 0x08  # boundary

            ground_tex = 0  # Ldrg
            ground_var = 0
            cliff_tex = 0
            cliff_var = 0
            layer = 0

            # 打包成 3 bytes
            b1 = (ground_height & 0x0F) | ((flags & 0x0F) << 4)
            b2 = ((ground_tex & 0x0F) | ((cliff_var & 0x07) << 4))
            b3 = ((ground_var & 0x1F) | ((cliff_tex & 0x0F) << 5) | ((layer & 0x0F) << 1))

            data += bytes([b1, b2, b3])

    # 悬崖数据
    data += struct.pack('<I', 0)  # 0 cliffs

    return bytes(data)


def create_w3u():
    """创建 war3map.w3u - 单位数据"""
    data = bytearray()
    data += struct.pack('<I', 1)  # version
    data += struct.pack('<I', 0)  # 0 custom units
    return bytes(data)


def create_w3a():
    """创建 war3map.w3a - 技能数据"""
    data = bytearray()
    data += struct.pack('<I', 1)  # version
    data += struct.pack('<I', 0)  # 0 custom abilities
    return bytes(data)


def create_w3t():
    """创建 war3map.w3t - 物品数据"""
    data = bytearray()
    data += struct.pack('<I', 1)  # version
    data += struct.pack('<I', 0)  # 0 custom items
    return bytes(data)


def create_doo():
    """创建 war3map.doo / war3mapUnits.doo"""
    data = bytearray()
    data += struct.pack('<I', 1)  # version
    data += struct.pack('<I', 0)  # 0 items
    return bytes(data)


def create_wts():
    """创建 war3map.wts - 字符串表"""
    data = bytearray()
    data += struct.pack('<I', 1)  # count
    data += struct.pack('<I', 4)  # offset[0]
    data += b'Hello RPG\x00'
    return bytes(data)


def create_jass(src_dir):
    """创建 war3map.j"""
    path = os.path.join(src_dir, 'war3map.j')
    if os.path.exists(path):
        with open(path, 'rb') as f:
            return f.read()

    # 最小 JASS (ASCII only)
    jass_code = b'''// Hello RPG - Wc3Forge Demo Map
// Compatible with WC3 1.27

globals
    unit hero = null
    player user = null
endglobals

function CreateHero takes nothing returns nothing
    set hero = CreateUnit(user, 'Hpal', 0, 0, 0)
    call SetUnitState(hero, UNIT_STATE_LIFE, 500.0)
    call SetUnitState(hero, UNIT_STATE_MAX_LIFE, 500.0)
    call SetHeroLevel(hero, 1, true)
endfunction

function main takes nothing returns nothing
    set user = Player(0)
    call CreateHero()
    call DisplayTextToPlayer(user, 0, 0, "=== Hello RPG ===")
    call DisplayTextToPlayer(user, 0, 0, "Welcome to Wc3Forge!")
    call DisplayTextToPlayer(user, 0, 0, "Map loaded!")
endfunction
'''
    return jass_code


def build_map(src_dir, output_path, width=32, height=32):
    """构建 WC3 地图"""

    print(f"构建 WC3 地图: {output_path}")
    print(f"地图尺寸: {width}x{height}")

    # 创建 MPQ 内容
    files = {
        'war3map.w3i': create_w3i_simple("Hello RPG", width, height),
        'war3map.w3e': create_w3e_simple(width, height),
        'war3map.w3u': create_w3u(),
        'war3map.w3a': create_w3a(),
        'war3map.w3t': create_w3t(),
        'war3map.doo': create_doo(),
        'war3mapUnits.doo': create_doo(),
        'war3map.wts': create_wts(),
        'war3map.j': create_jass(src_dir),
    }

    for name, data in files.items():
        print(f"  {name}: {len(data)} bytes")

    # 计算 MPQ 大小
    mpq_size = sum(len(d) for d in files.values())
    print(f"\nMPQ 大小: {mpq_size} bytes")

    # 准备字符串
    name = "Hello RPG"
    author = "Wc3Forge"
    desc = "Demo map"

    name_bytes = name.encode('gbk')
    author_bytes = author.encode('gbk')
    desc_bytes = desc.encode('gbk')

    # 创建 HM3W 文件
    with open(output_path, 'wb') as f:
        # === HM3W 头 (512 字节) ===
        header = bytearray(512)

        # 签名 "HM3W"
        header[0:4] = HM3W_SIGNATURE

        # 版本 (offset 4) - WC3 1.27 使用 0
        struct.pack_into('<I', header, 4, 0)

        # 地图 ID (offset 8) - 固定值
        struct.pack_into('<I', header, 8, 0x149C0000)

        # 名称长度 (offset 16)
        struct.pack_into('<I', header, 16, len(name_bytes))

        # MPQ 偏移 (offset 20) - 固定 131072
        struct.pack_into('<I', header, 20, 512)

        # 名称 (offset 32, 64 bytes)
        header[32:32+len(name_bytes)] = name_bytes

        # 作者 (offset 96, 64 bytes)
        header[96:96+len(author_bytes)] = author_bytes

        # 描述 (offset 160, 128 bytes)
        header[160:160+len(desc_bytes)] = desc_bytes

        # 尺寸 (offset 300)
        struct.pack_into('<HH', header, 300, width, height)

        # 地图大小 (offset 304)
        map_size = width * height * 256
        struct.pack_into('<I', header, 304, map_size)

        # tileset (offset 308)
        header[308:309] = b'L'

        # MPQ 大小 (offset 312)
        struct.pack_into('<I', header, 312, mpq_size)

        f.write(bytes(header))

        # 写入 MPQ 签名和头部
        mpq_header = bytearray(32)
        mpq_header[0:4] = b'MPQ\x1a'
        struct.pack_into('<I', mpq_header, 4, 32)  # header size
        struct.pack_into('<I', mpq_header, 8, 4)   # version
        struct.pack_into('<I', mpq_header, 12, 512)  # sector size
        struct.pack_into('<I', mpq_header, 16, mpq_size)  # archive size
        struct.pack_into('<I', mpq_header, 20, 0)   # hash table offset
        struct.pack_into('<I', mpq_header, 24, 0)   # block table offset
        struct.pack_into('<I', mpq_header, 28, 0x1100)  # hash table size (512 entries)
        struct.pack_into('<I', mpq_header, 32, 0x1100)  # block table size (512 entries) - 偏移28是4字节，所以32开始
        f.write(bytes(mpq_header))

        # === MPQ 内容 (从偏移 512 + 32 = 544) ===
        for data in files.values():
            f.write(data)

    print(f"\n地图构建完成: {output_path}")
    print(f"文件大小: {os.path.getsize(output_path)} bytes")

    return True


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='WC3 地图构建器')
    parser.add_argument('--src', default='sample_map/src')
    parser.add_argument('--output', default='sample_map/hello_rpg.w3x')
    parser.add_argument('--width', type=int, default=32)
    parser.add_argument('--height', type=int, default=32)
    args = parser.parse_args()

    build_map(args.src, args.output, args.width, args.height)